branches:
  only:
  - stable
dist: trusty
sudo: required
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - qt4-dev-tools 
            - libboost-all-dev
            - g++-6
            - python2.7
            - libopenmpi-dev
            - libvtk6-dev
            - libpq-dev
            - doxygen
git:
    depth: 3

# Test the build with VTK, ParaView and different combinations of
# the TTK build options
matrix:
    include:
        # Just base code
        - env:
            - TTK_BUILD_VTK_WRAPPERS=OFF
            - TTK_BUILD_PARAVIEW_PLUGINS=OFF
            - TTK_BUILD_STANDALONE_APPS=OFF
            - TTK_ENABLE_KAMIKAZE=OFF
            - TTK_ENABLE_MPI=OFF
            - TTK_ENABLE_OPENMP=OFF
        # Base code + OpenMP
        - env:
            - TTK_BUILD_VTK_WRAPPERS=ON
            - TTK_BUILD_PARAVIEW_PLUGINS=OFF
            - TTK_BUILD_STANDALONE_APPS=OFF
            - TTK_ENABLE_KAMIKAZE=OFF
            - TTK_ENABLE_MPI=OFF
            - TTK_ENABLE_OPENMP=ON
        # Base code + VTK + OpenMP + APPS + DOC
        - env:
            - TTK_BUILD_DOCUMENTATION=ON
            - TTK_BUILD_VTK_WRAPPERS=ON
            - TTK_BUILD_PARAVIEW_PLUGINS=OFF
            - TTK_BUILD_STANDALONE_APPS=ON
            - TTK_ENABLE_KAMIKAZE=OFF
            - TTK_ENABLE_MPI=OFF
            - TTK_ENABLE_OPENMP=ON
#        # Base code, VTK wrappers, apps, ParaView plugins
#       - env:
#           - TTK_BUILD_VTK_WRAPPERS=ON
#           - TTK_BUILD_PARAVIEW_PLUGINS=ON
#           - TTK_BUILD_STANDALONE_APPS=ON
#           - TTK_ENABLE_KAMIKAZE=OFF
#           - TTK_ENABLE_MPI=OFF
#           - TTK_ENABLE_OPENMP=ON
#       # Base code, VTK wrappers, ParaView plugins
#       - env:
#           - TTK_BUILD_PARAVIEW_PLUGINS=ON
#           - TTK_BUILD_STANDALONE_APPS=ON
#           - TTK_BUILD_STANDALONE_APPS=ON
#           - TTK_ENABLE_KAMIKAZE=OFF
#           - TTK_ENABLE_MPI=OFF
#           - TTK_ENABLE_OPENMP=ON


before_install:
    - export CC=gcc-6
    - export CXX=g++-6
    - mkdir ext && cd ext
    - wget "https://cmake.org/files/v3.9/cmake-3.9.2-Linux-x86_64.sh"
    - chmod +x ./cmake-3.9.2-Linux-x86_64.sh
    - printf "y\ny" | ./cmake-3.9.2-Linux-x86_64.sh > /dev/null
    - export PATH=`pwd`/cmake-3.9.2-Linux-x86_64/bin/:$PATH
    - ../.travis-setup-dependencies.sh
    - export ParaView_DIR=`pwd`/ParaView-v5.4.0/install/lib/cmake/paraview-5.4/
    - cd ../
    # fixes broken vtk package in trusty
    - sudo ln -sf /usr/lib/x86_64-linux-gnu/libpq.so.5 /usr/lib/libpq.so

script:
    - mkdir build
    - cd build
    - cmake
      -DCMAKE_INSTALL_PREFIX=../install
      -DTTK_BUILD_DOCUMENTATION=$TTK_BUILD_DOCUMENTATION
      -DTTK_BUILD_VTK_WRAPPERS=$TTK_BUILD_VTK_WRAPPERS
      -DTTK_BUILD_PARAVIEW_PLUGINS=$TTK_BUILD_PARAVIEW_PLUGINS
      -DTTK_BUILD_STANDALONE_APPS=$TTK_BUILD_STANDALONE_APPS
      -DTTK_ENABLE_KAMIKAZE=$TTK_ENABLE_KAMIKAZE
      -DTTK_ENABLE_MPI=$TTK_ENABLE_MPI
      -DTTK_ENABLE_OPENMP=$TTK_ENABLE_OPENMP
      -DParaView_DIR=$ParaView_DIR
      ..
    - cmake --build . --target install

