version: 2
jobs:
  build-and-test:
    working_directory: ~/RTK-build
    docker:
      - image: insighttoolkit/module-ci:latest
    steps:
      - checkout:
          path: ~/RTK
      - run:
          name: Build and Test
          no_output_timeout: 1.0h
          command: |
            ctest -j 2 -VV -C Release \
              -S ~/RTK/cmake/ci_ctest.config \
              -D GENERATOR="Unix Makefiles" \
              -D SRC_DIR="~/RTK" \
              -D BIN_DIR="~/RTK-build" \
              -D CONFIG_TYPE="MinSizeRel" \
              -D ITK_DIR="~/ITK-build" \
              -D SITE="CircleCI" \
              -D BRANCH_NAME="${CIRCLE_BRANCH}" \
              -D PULL_REQUEST_NUMBER="${CIRCLE_PR_NUMBER}" \
workflows:
    version: 2
    build-test:
      jobs:
        - build-and-test
