name: packaging

on:
  push:
    branch-ignore:
      - '*'
    tags:
      - 'v*'
      - 'dev*'
      - '*-*-*'
      - '*.*.*'
      - 'pack*'

env:
  PV_TAG: v5.10.1
  PV_REPO: topology-tool-kit/ttk-paraview

jobs:

  # -------------#
  # Build Ubuntu #
  # -------------#
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v2
      name: Checkout TTK source code

    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        # TTK dependencies
        sudo apt install -y \
          libboost-system-dev \
          libeigen3-dev \
          libgraphviz-dev \
          libsqlite3-dev \
          libgl1-mesa-dev \
          graphviz \
          python3-sklearn \
          zlib1g-dev \
          dpkg-dev

    - name: Install optional dependencies
      uses: ./.github/actions/install-deps-unix

    - uses: dsaltares/fetch-gh-release-asset@master
      name: Fetch TTK-ParaView package
      with:
        repo: "${{ env.PV_REPO }}"
        version: "tags/${{ env.PV_TAG }}"
        file: "ttk-paraview-${{ env.PV_TAG }}-${{ matrix.os }}.deb"
        target: "ttk-paraview.deb"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install ParaView .deb
      run: |
        sudo apt install ./ttk-paraview.deb

    - name: Create & configure TTK build directory
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DTTK_BUILD_PARAVIEW_PLUGINS=TRUE \
          -DTTK_BUILD_VTK_WRAPPERS=TRUE \
          -DTTK_BUILD_STANDALONE_APPS=TRUE \
          -DTTK_ENABLE_KAMIKAZE=TRUE \
          -DTTK_ENABLE_DOUBLE_TEMPLATING=FALSE \
          -DTTK_ENABLE_CPU_OPTIMIZATION=FALSE \
          -DTTK_ENABLE_SHARED_BASE_LIBRARIES=TRUE \
          $GITHUB_WORKSPACE

    - name: Build TTK
      run: |
        cd build
        # not enough RAM to build in parallel (or with ninja)
        cmake --build .

    - name: Package TTK & update package informations
      run: |
        cd build
        cpack -G DEB

    - name: Upload TTK .deb package
      uses: actions/upload-artifact@v2
      with:
        name: ttk-${{ matrix.os }}.deb
        path: build/ttk.deb

  # ------------#
  # Test Ubuntu #
  # ------------#
  test-linux:
    needs: build-linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v2
      name: Checkout TTK source code

    - uses: dsaltares/fetch-gh-release-asset@master
      name: Fetch TTK-ParaView package
      with:
        repo: "${{ env.PV_REPO }}"
        version: "tags/${{ env.PV_TAG }}"
        file: "ttk-paraview-${{ env.PV_TAG }}-${{ matrix.os }}.deb"
        target: "ttk-paraview.deb"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch TTK .deb artifact
      uses: actions/download-artifact@v2
      with:
        name: ttk-${{ matrix.os }}.deb

    - name: Install generated .deb packages
      run: |
        sudo apt update
        sudo apt install ./ttk-paraview.deb
        sudo apt install ./ttk.deb

    - name: Set PYTHONPATH for Ubuntu 22.04 pvpython
      if: matrix.os == 'ubuntu-22.04'
      run: |
        # pvpython does not embed the correct PYTHONPATH
        echo "PYTHONPATH=/usr/lib/python3/dist-packages:$PYTHONPATH" >> $GITHUB_ENV

    - name: Run TTK tests
      uses: ./.github/actions/test-ttk-unix

    - uses: actions/checkout@v2
      with:
        repository: "topology-tool-kit/ttk-data"
        ref: "dev"
        path: "ttk-data"
      name: Checkout ttk-data

    - name: Run ttk-data Python scripts [NOT ENFORCED]
      continue-on-error: true
      run: |
        cd ttk-data
        python3 -u python/run.py
        cat python/res.json
        diff python/hashes/${{ matrix.os }}.json python/res.json
      env:
        OMP_NUM_THREADS: 1


  # ------------#
  # Build macOS #
  # ------------#
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout TTK source code

    - name: Remove hosted Python
      run: |
        sudo rm -rf /usr/local/Frameworks/Python.framework

    - name: Install macOS dependencies
      run: |
        # ParaView dependencies
        brew install --cask xquartz
        brew install wget libomp mesa glew qt@5 ninja python
        # TTK dependencies
        brew install boost eigen graphviz embree
        python3 -m pip install scikit-learn packaging

    - name: Install optional dependencies
      uses: ./.github/actions/install-deps-unix

    - name: Fetch & install TTK-ParaView
      run: |
        wget https://github.com/${{ env.PV_REPO }}/releases/download/${{ env.PV_TAG }}/ttk-paraview-${{ env.PV_TAG }}.pkg
        sudo installer -pkg ttk-paraview-${{ env.PV_TAG }}.pkg -target /

    - name: Create & configure TTK build directory
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DQt5_DIR=$(brew --prefix qt@5)/lib/cmake/Qt5 \
          -DPython3_FIND_STRATEGY=LOCATION \
          -DPython3_ROOT_DIR=$(brew --prefix python) \
          -DTTK_BUILD_PARAVIEW_PLUGINS=TRUE \
          -DTTK_BUILD_VTK_WRAPPERS=TRUE \
          -DTTK_BUILD_STANDALONE_APPS=TRUE \
          -DTTK_ENABLE_KAMIKAZE=TRUE \
          -DTTK_ENABLE_DOUBLE_TEMPLATING=TRUE \
          -DTTK_ENABLE_CPU_OPTIMIZATION=FALSE \
          -DTTK_ENABLE_SHARED_BASE_LIBRARIES=TRUE \
          -GNinja \
          $GITHUB_WORKSPACE

    - name: Build TTK
      run: |
        cd build
        cmake --build . --parallel

    - name: Package TTK
      run: |
        cd build
        cpack -G productbuild

    - name: Upload .pkg package
      uses: actions/upload-artifact@v2
      with:
        name: ttk.pkg
        path: build/ttk.pkg

  # -----------#
  # Test macOS #
  # -----------#
  test-macos:
    needs: build-macos
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout TTK source code

    - name: Remove hosted Python
      run: |
        sudo rm -rf /usr/local/Frameworks/Python.framework

    - name: Install macOS dependencies
      run: |
        # ParaView dependencies
        brew install --cask xquartz
        brew install wget libomp mesa glew qt@5 ninja python
        # TTK dependencies
        brew install boost eigen graphviz embree
        python3 -m pip install scikit-learn packaging

    - name: Fetch TTK-ParaView
      run: |
        wget https://github.com/${{ env.PV_REPO }}/releases/download/${{ env.PV_TAG }}/ttk-paraview-${{ env.PV_TAG }}.pkg

    - name: Fetch TTK .pkg artifact
      uses: actions/download-artifact@v2
      with:
        name: ttk.pkg

    - name: Install .pkg packages
      run: |
        sudo installer -pkg ttk-paraview-${{ env.PV_TAG }}.pkg -target /
        sudo installer -pkg ttk.pkg -target /

    - name: Test TTK examples
      run: |
        # base layer
        cd $GITHUB_WORKSPACE/examples/c++
        mkdir build && cd build
        cmake ..
        cmake --build . --parallel
        ./ttkExample-c++ -i ../../data/inputData.off
        # VTK layer
        export CMAKE_PREFIX_PATH=$(brew --prefix qt@5)/lib/cmake:$CMAKE_PREFIX_PATH
        cd $GITHUB_WORKSPACE/examples/vtk-c++
        mkdir build &&  cd build
        cmake ..
        cmake --build . --parallel
        ./ttkExample-vtk-c++ -i ../../data/inputData.vtu
        # pure Python
        export PYTHONPATH=/Applications/lib/python3.9/site-packages
        export DYLD_LIBRARY_PATH=/Applications/lib:$DYLD_LIBRARY_PATH
        cd $GITHUB_WORKSPACE/examples/python
        python3 example.py ../data/inputData.vtu
        # pvpython
        export PATH=/Applications/bin:$PATH
        cd $GITHUB_WORKSPACE/examples/pvpython
        pvpython example.py ../data/inputData.vtu
        # standalones
        cd $GITHUB_WORKSPACE
        ttkHelloWorldCmd -i examples/data/inputData.vtu

    - uses: actions/checkout@v2
      with:
        repository: "topology-tool-kit/ttk-data"
        ref: "dev"
        path: "ttk-data"
      name: Checkout ttk-data

    - name: Run ttk-data Python scripts [NOT ENFORCED]
      continue-on-error: true
      run: |
        cd ttk-data
        python3 -u python/run.py
        cat python/res.json
        diff python/hashes/macOS.json python/res.json
      env:
        PYTHONPATH: /Applications/lib/python3.9/site-packages
        PV_PLUGIN_PATH: /Applications/bin/plugins/TopologyToolKit
        OMP_NUM_THREADS: 1


  # --------------#
  # Build Windows #
  # --------------#
  build-windows:
    runs-on: windows-2022
    env:
      CONDA_ROOT: C:\Miniconda
    steps:
    - uses: actions/checkout@v2
      name: Checkout TTK source code

    - uses: s-weigand/setup-conda@v1

    - name: Install dependencies with conda
      shell: bash
      run: |
        conda install -c conda-forge "qt>=5.12" boost eigen spectralib zfp \
          scikit-learn packaging openmp "graphviz>=2.50"

    - name: Remove hosted Python
      shell: bash
      run: |
        rm -rf C:/hostedtoolcache/windows/Python

    - name: Fetch TTK-ParaView installer
      run: |
        Invoke-WebRequest `
        -OutFile ttk-paraview.exe `
        -Uri https://github.com/${{ env.PV_REPO }}/releases/download/${{ env.PV_TAG }}/ttk-paraview-${{ env.PV_TAG }}.exe

    - name: Install ParaView
      shell: cmd
      run: |
        ttk-paraview.exe /S

    - name: Fetch Visual C++ redistribuable run-time
      run: |
        Invoke-WebRequest `
          -OutFile vc_redist.x64.exe `
          -Uri https://aka.ms/vs/16/release/vc_redist.x64.exe

    - name: Create & configure TTK build directory
      shell: cmd
      run: |
        set CMAKE_PREFIX_PATH=%CONDA_ROOT%\Library\lib\cmake;%CONDA_ROOT%\Library\share\eigen3\cmake;%CONDA_ROOT%\Library\cmake;%ProgramFiles%\TTK-ParaView\lib\cmake
        mkdir build
        cd build
        cmake ^
          -DCMAKE_POLICY_DEFAULT_CMP0092=NEW ^
          -DBUILD_SHARED_LIBS:BOOL=TRUE ^
          -DCMAKE_INSTALL_PREFIX="%ProgramFiles%\TTK" ^
          -DPython3_ROOT_DIR="%CONDA_ROOT%" ^
          -DGraphviz_INCLUDE_DIR="%CONDA_ROOT%\Library\include\graphviz" ^
          -DGraphviz_CDT_LIBRARY="%CONDA_ROOT%\Library\lib\cdt.lib" ^
          -DGraphviz_GVC_LIBRARY="%CONDA_ROOT%\Library\lib\gvc.lib" ^
          -DGraphviz_CGRAPH_LIBRARY="%CONDA_ROOT%\Library\lib\cgraph.lib" ^
          -DGraphviz_PATHPLAN_LIBRARY="%CONDA_ROOT%\Library\lib\pathplan.lib" ^
          -DTTK_BUILD_PARAVIEW_PLUGINS=TRUE ^
          -DTTK_BUILD_VTK_WRAPPERS=TRUE ^
          -DTTK_BUILD_STANDALONE_APPS=TRUE ^
          -DTTK_ENABLE_KAMIKAZE=TRUE ^
          -DTTK_ENABLE_DOUBLE_TEMPLATING=FALSE ^
          -DTTK_ENABLE_OPENMP=TRUE ^
          -DTTK_ENABLE_CPU_OPTIMIZATION=FALSE ^
          -DTTK_ENABLE_SHARED_BASE_LIBRARIES=TRUE ^
          -G"Visual Studio 17 2022" ^
          -Tclangcl ^
          ..

    - name: Build TTK
      shell: bash
      run: |
        cd build
        cmake --build . --config Release --parallel

    - name: Package TTK
      shell: bash
      run: |
        cd build
        cpack -C Release -G NSIS64

    - name: Upload TTK .exe package
      uses: actions/upload-artifact@v2
      with:
        name: ttk.exe
        path: build/ttk.exe

  # -------------#
  # Test Windows #
  # -------------#
  test-windows:
    needs: build-windows
    runs-on: windows-2022
    env:
      PV_DIR: C:\Program Files\TTK-ParaView
      TTK_DIR: C:\Program Files\TTK
      CONDA_ROOT: C:\Miniconda
    steps:
    - uses: actions/checkout@v2
      name: Checkout TTK source code

    - uses: s-weigand/setup-conda@v1

    - name: Install dependencies with conda
      shell: bash
      run: |
        conda install -c conda-forge "qt>=5.12" boost eigen spectralib zfp \
          scikit-learn packaging openmp "graphviz>=2.50"

    - name: Remove hosted Python
      shell: bash
      run: |
        rm -rf C:/hostedtoolcache/windows/Python

    - name: Fetch TTK-ParaView installer
      run: |
        Invoke-WebRequest `
        -OutFile ttk-paraview.exe `
        -Uri https://github.com/${{ env.PV_REPO }}/releases/download/${{ env.PV_TAG }}/ttk-paraview-${{ env.PV_TAG }}.exe

    - name: Fetch TTK .exe artifact
      uses: actions/download-artifact@v2
      with:
        name: ttk.exe

    - name: Install TTK-ParaView and TTK
      shell: cmd
      run: |
        ttk-paraview.exe /S
        ttk.exe /S

    - name: Set PATH environment variable
      shell: bash
      run: |
        echo "$PV_DIR/bin" >> $GITHUB_PATH
        echo "$TTK_DIR/bin" >> $GITHUB_PATH

    - name: Test C++ example
      shell: cmd
      run: |
        set CMAKE_PREFIX_PATH=%TTK_DIR%\lib\cmake;%PV_DIR%\lib\cmake
        cd %GITHUB_WORKSPACE%\examples\c++
        mkdir build
        cd build
        cmake -G"Visual Studio 17 2022" -Tclangcl ..
        cmake --build . --config Release --parallel
        Release\ttkExample-c++.exe -i ..\..\data\inputData.off

    - name: Test VTK-C++ example
      shell: cmd
      run: |
        set CMAKE_PREFIX_PATH=%TTK_DIR%\lib\cmake;%PV_DIR%\lib\cmake
        cd %GITHUB_WORKSPACE%\examples\vtk-c++
        mkdir build
        cd build
        cmake -G"Visual Studio 17 2022" -Tclangcl ..
        cmake --build . --config Release --parallel
        Release\ttkExample-vtk-c++.exe -i ..\..\data\inputData.vtu

    - name: Test Python example
      shell: cmd
      run: |
        set PYTHONPATH=%PV_DIR%\bin\Lib\site-packages;%TTK_DIR%\bin\Lib\site-packages;%CONDA_ROOT%\Lib
        cd %GITHUB_WORKSPACE%\examples\python
        python example.py ..\data\inputData.vtu

    - name: Test pvpython example
      shell: cmd
      run: |
        set PYTHONPATH=%CONDA_ROOT%\Lib
        set PV_PLUGIN_PATH=%TTK_DIR%\bin\plugins
        cd %GITHUB_WORKSPACE%\examples\pvpython
        pvpython.exe example.py ..\data\inputData.vtu

    - name: Test standalone
      shell: cmd
      run: |
        cd %GITHUB_WORKSPACE%\examples\vtk-c++
        ttkHelloWorldCmd.exe -i %GITHUB_WORKSPACE%\examples\data\inputData.vtu

    - uses: actions/checkout@v2
      with:
        repository: "topology-tool-kit/ttk-data"
        ref: "dev"
        path: "ttk-data"
      name: Checkout ttk-data

    - name: Run ttk-data Python scripts [NOT ENFORCED]
      continue-on-error: true
      shell: cmd
      run: |
        set PYTHONPATH=%PV_DIR%\bin\Lib\site-packages;%TTK_DIR%\bin\Lib\site-packages;%CONDA_ROOT%\Lib
        set PV_PLUGIN_PATH=%TTK_DIR%\bin\plugins
        cd ttk-data
        python -u python\run.py
        type python\res.json
        FC python\hashes\windows.json python\res.json
      env:
        OMP_NUM_THREADS: 1


  # ---------------#
  # Create release #
  # ---------------#
  create-release:
    runs-on: ubuntu-latest
    needs: [test-linux, test-macos, test-windows]
    steps:

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

    - name: Fetch all uploaded artifacts
      uses: actions/download-artifact@v2

    - name: Upload Ubuntu Focal .deb as Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ttk-ubuntu-20.04.deb/ttk.deb
        asset_name: ttk-$tag-ubuntu-20.04.deb

    - name: Upload Ubuntu Jammy .deb as Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ttk-ubuntu-22.04.deb/ttk.deb
        asset_name: ttk-$tag-ubuntu-22.04.deb

    - name: Upload macOS .pkg as Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ttk.pkg/ttk.pkg
        asset_name: ttk-$tag.pkg

    - name: Upload Windows .exe as Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ttk.exe/ttk.exe
        asset_name: ttk-$tag.exe
